#FROM postgres:latest

# Add initialization scripts or setup steps specific to your needs
# COPY init-scripts/ /docker-entrypoint-initdb.d/

# Expose a different port for each container (optional)
#EXPOSE 5432

FROM alpine:3.8
ENTRYPOINT ["echo"]
CMD ["Hello World!"]